
threads: 16
seed: [54232]
window: 1000
trim_sequences: true
pre_align: true
run_trust4: true
run_trust4_bam: true
run_mixcr: true
run_saturation: true

species: "Canis_lupus_familiaris"
index: "data/refs/canfam4/canfam4"
index_bam: "data/refs/ensembl/bowtie2/genome_cfam1_ensembl"

# The repertoire_assembly pipeline assumes that for a sample
# both end files have names of the form
# dict[sample] + "_R1" + {suffix}
# dict[sample] + "_R2" + {suffix}
suffix: "_001.fastq.gz"
samples: {
  "run1_bio1_tech1": "data/run1/K9013v01-rxn1_S425_L003",
  "run1_bio1_tech2": "data/run1/K9013v01-rxn2_S426_L003",
  "run1_bio2_tech1": "data/run1/K9013rcc-rxn3_S423_L003",
  "run1_bio2_tech2": "data/run1/K9013rcc-rxn4_S424_L003",
  "run2_bio1_tech1": "data/run2/K9013v01-rxn1_S164_L001",
  "run2_bio1_tech2": "data/run2/K9013v01-rxn2_S165_L001",
  "run2_bio2_tech1": "data/run2/K9013rcc-rxn3_S162_L001",
  "run2_bio2_tech2": "data/run2/K9013rcc-rxn4_S163_L001",
  "run3_bio1_tech1": "data/run3/K9013v01-rxn1_S202_L001",
  "run3_bio1_tech2": "data/run3/K9013v01-rxn2_S203_L001",
  "run3_bio2_tech1": "data/run3/K9013rcc-rxn3_S200_L001",
  "run3_bio2_tech2": "data/run3/K9013rcc-rxn4_S201_L001",
  "merged_bio1_tech1": "data/merged/K9013v01-rxn1",
  "merged_bio1_tech2": "data/merged/K9013v01-rxn2",
  "merged_bio2_tech1": "data/merged/K9013rcc-rxn3",
  "merged_bio2_tech2": "data/merged/K9013rcc-rxn4",
  "prev_run1": "data/previous/K9013-01",
  "prev_run2": "data/previous/K9013-02_S112_L002"}

mixcr_samples: {
  "run1_bio1_tech1": "data/run1/K9013v01-rxn1_S425_L003",
  "run1_bio1_tech2": "data/run1/K9013v01-rxn2_S426_L003",
  "run1_bio2_tech1": "data/run1/K9013rcc-rxn3_S423_L003",
  "run1_bio2_tech2": "data/run1/K9013rcc-rxn4_S424_L003",
  "run2_bio1_tech1": "data/run2/K9013v01-rxn1_S164_L001",
  "run2_bio1_tech2": "data/run2/K9013v01-rxn2_S165_L001",
  "run2_bio2_tech1": "data/run2/K9013rcc-rxn3_S162_L001",
  "run2_bio2_tech2": "data/run2/K9013rcc-rxn4_S163_L001",
  "run3_bio1_tech1": "data/run3/K9013v01-rxn1_S202_L001",
  "run3_bio1_tech2": "data/run3/K9013v01-rxn2_S203_L001",
  "run3_bio2_tech1": "data/run3/K9013rcc-rxn3_S200_L001",
  "run3_bio2_tech2": "data/run3/K9013rcc-rxn4_S201_L001"}


# trimmomatic parameters
qc:
  trimmer: ["TRAILING:20", "MINLEN:100"]


saturation:
  bootstrap_replicates: 100 # 200
  samples: ["run3_bio1_tech1", "run3_bio1_tech2"]
  seq_depth_blocks: 100000 # pairs of sequences
  perc_med_width: 0.5
  perc_overlap_width: 0.25

trust4:
  barcode_range: 59
  read1_range: 22
  read2_range: 22
  filter_tcr_error: 0.01

mixcr:
  # params: "rnaseq-cdr3 --species dog -b imgt.202214-2 --rna" # more presets can be seen https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/
  params: "rnaseq-cdr3 --species dog -b imgt.202214-2 --rna --floating-left-alignment-boundary --floating-right-alignment-boundary C"