
# general configuration files
threads: 16
samplefile: "samples.csv"
seed: [54232]
run_mixcr: true
run_saturation: true
run_report: false

# The repertoire_assembly pipeline assumes that for a sample
# both end files have names of the form
# dict[sample] + "_R1" + {suffix}
# dict[sample] + "_R2" + {suffix}
suffix: "_001.fastq.gz"

# docker images
docker:
  run_line: "docker run -v $(pwd):$(pwd) -w $(pwd) -u $(id -u):$(id -g)"
  fastqc: "staphb/fastqc"
  multiqc: "staphb/multiqc"
  trimmomatic: "staphb/trimmomatic"
  rquarto: "tcr/satcr"
  mixcr: "ghcr.io/milaboratory/mixcr/mixcr:latest"


# trimmomatic parameters
trim:
  trimmer: ["TRAILING:20", "MINLEN:100"]

mixcr:
  params: "rna-seq --species dog -b imgt.202214-2 --rna" # more presets can be seen https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/
  # params: "rnaseq-cdr3 --species dog -b imgt.202214-2 --rna --floating-left-alignment-boundary --floating-right-alignment-boundary C"
  license_file: "/path/to/license/file"
  
saturation:
  bootstrap_replicates: 3 # 200
  samples: ["run1_bio1_tech1", "run1_bio1_tech2"]
  # only one of block_size or nblocks is supposed to be Null
  block_size: Null
  nblocks: 10
